import {
  PiDesktop,
  PiCloud,
  PiShield,
  PiDatabase,
  PiNetworkX,
  PiChartBar,
  PiRadio,
  PiGlobeHemisphereWest,
  PiRobot,
  PiMonitor,
  PiTerminal,
  PiPhone,
  PiCode,
  PiPackage,
  PiWarningCircle,
  PiEnvelope,
  PiShieldCheck,
  PiGearSix,
  PiHeadphones,
  PiBuilding,
  PiLifebuoy,
  PiFile,
  PiAppleLogo,
  PiLightbulb,
  PiPulse,
} from 'react-icons/pi';
import type { ComponentType } from 'react';

/**
 * Centralized icon map for use across components.
 * Maps icon names (strings) to their corresponding icon components.
 * Primary source is Phosphor icons (react-icons/pi), with fallback to lucide-react for missing icons.
 */
export const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  Server: PiDesktop,
  Cloud: PiCloud,
  Database: PiDatabase,
  Network: PiNetworkX,
  Radio: PiRadio,
  BarChart3: PiChartBar,
  Shield: PiShield,
  Globe: PiGlobeHemisphereWest,
  Bot: PiRobot,
  Monitor: PiMonitor,
  Terminal: PiTerminal,
  Apple: PiAppleLogo,
  Phone: PiPhone,
  Code2: PiCode,
  Boxes: PiPackage,
  ShieldAlert: PiWarningCircle,
  Mail: PiEnvelope,
  ShieldCheck: PiShieldCheck,
  CloudCog: PiGearSix,
  Headphones: PiHeadphones,
  Building2: PiBuilding,
  Lightbulb: PiLightbulb,
  LifeBuoy: PiLifebuoy,
  FileCheck: PiFile,
  Activity: PiPulse,
};
