#!/usr/bin/env node
import assert from 'node:assert/strict';
import { readFile, writeFile, readdir } from 'node:fs/promises';

const definitions = JSON.parse(await readFile(new URL('../editorial/collections.json', import.meta.url), 'utf8'));
const seoFields = JSON.parse(await readFile(new URL('../editorial/seo.json', import.meta.url), 'utf8'));
const target = new URL('../src/schemas.ts', import.meta.url);
function schema(field) {
  let result;
  switch (field.type) {
    case 'group': result = field.ref === 'seo' && !field.fields ? 'seoSchema' : object({ ...(field.ref === 'seo' ? seoFields : {}), ...field.fields }); break;
    case 'number': result = 'z.number()'; break;
    case 'boolean': result = 'z.boolean()'; break;
    case 'date': result = 'z.date()'; break;
    case 'strings': result = 'z.array(z.string())'; break;
    case 'select':
      assert(field.choices?.length, 'Select requires choices');
      result = `z.enum(${JSON.stringify(field.choices)})`; break;
    case 'text': case 'textarea': case 'url': case 'media': result = 'z.string()'; break;
    default: throw new Error(`Unknown collection field type: ${field.type}`);
  }
  if (field.optional) result += '.optional()';
  if (Object.hasOwn(field, 'default')) result += `.default(${JSON.stringify(field.default)})`;
  return result;
}
function object(fields) {
  return `z.object({\n${Object.entries(fields).map(([key, field]) => `  ${JSON.stringify(key)}: ${schema(field)},`).join('\n')}\n})`;
}
// Public names are API compatibility aliases, not field contracts.
const types = { services: 'Service', blog: 'BlogPost', locations: 'Location', testimonials: 'Testimonial', partners: 'Partner', pseoServices: 'PseoService', pseoIndustries: 'PseoIndustry' };
const source = `// Generated by scripts/collections.mjs from editorial/collections.json and editorial/seo.json; do not edit.\nimport { z } from 'zod/v4';\n\nexport const seoSchema = ${object(seoFields)};\nexport type SEO = z.infer<typeof seoSchema>;\n\n${Object.entries(definitions).map(([name, definition]) => `export const ${name}Schema = ${object(definition.fields)};`).join('\n\n')}\n\nexport const collectionSchemas = {\n${Object.keys(definitions).map(name => `  ${name}: ${name}Schema,`).join('\n')}\n} as const;\nexport type CollectionName = keyof typeof collectionSchemas;\nexport type CollectionData<K extends CollectionName> = z.infer<(typeof collectionSchemas)[K]>;\n${Object.entries(types).map(([name, type]) => `export type ${type} = z.infer<typeof ${name}Schema>;`).join('\n')}\n`;
if (process.argv.includes('--check') || process.argv.includes('--exercise')) {
  assert.equal((await readFile(target, 'utf8')).replace(/\r\n/g, '\n'), source, 'Collection schema drift: run generate:collections');
  console.log('Collection generation: no drift');
} else {
  await writeFile(target, source);
  console.log('Generated src/schemas.ts');
}
if (process.argv.includes('--exercise')) {
  const { collectionSchemas } = await import('../src/schemas.ts');
  const { load } = await import('js-yaml');
  let count = 0;
  for (const [name, definition] of Object.entries(definitions)) {
    const directory = new URL(`../../../apps/bdkinc/src/content/${name}/`, import.meta.url);
    let retained = 0;
    for (const file of (await readdir(directory)).filter(file => !file.startsWith('_') && /\.(json|md|mdx)$/.test(file)).sort()) {
      const text = await readFile(new URL(file, directory), 'utf8');
      const data = file.endsWith('.json') ? JSON.parse(text) : load(text.match(/^---\r?\n([\s\S]*?)\r?\n---/)[1]);
      if (typeof data.pubDate === 'string') data.pubDate = new Date(data.pubDate);
      const parser = collectionSchemas[name];
      const parsed = parser.parse(data);
      assert.deepEqual(parsed, Object.fromEntries(Object.entries(data).filter(([key]) => Object.hasOwn(definition.fields, key)).concat(!Object.hasOwn(data, 'category') && name === 'blog' ? [['category', 'Infrastructure']] : [])));
      const minimal = { ...data, ...definition.creationDefaults };
      for (const [key, field] of Object.entries(definition.fields)) {
        if (field.optional || Object.hasOwn(field, 'default')) delete minimal[key];
        if (field.type === 'select') assert.equal(parser.safeParse({ ...data, [key]: '__invalid__' }).success, false);
      }
      const result = parser.parse({ ...minimal, __unknown: true });
      assert.equal(Object.hasOwn(result, '__unknown'), false);
      if (name === 'blog') {
        assert.equal(result.category, 'Infrastructure');
        assert.equal(parser.safeParse({ ...data, pubDate: data.pubDate.toISOString() }).success, false);
      }
      for (const key of Object.keys(definition.creationDefaults ?? {})) assert.deepEqual(parsed[key], data[key]);
      retained++; count++;
    }
    console.log(`${name}: ${retained} retained fixtures; optional/default/enum/creation/strip checks passed`);
  }
  const { pageDefinitions, pageSchemas, settingsDefinition, settingsSchema } = await import('../src/editorial.ts');
  for (const [key, definition] of Object.entries(pageDefinitions)) {
    const parser = pageSchemas[key];
    parser.parse(definition.defaults);
    const group = definition.fields.seo ? 'seo' : 'metadata';
    if (!definition.fields[group].optional) {
      const missing = { ...definition.defaults };
      delete missing[group];
      assert.equal(parser.safeParse(missing).success, false);
    }
    const data = { ...definition.defaults, [group]: { ...definition.defaults[group], noindex: false, image: '/social.jpg', imageAlt: 'Social image' } };
    parser.parse(data);
    assert.equal(parser.safeParse({ ...data, [group]: { ...data[group], noindex: 'false' } }).success, false);
    assert.equal(parser.safeParse({ ...data, [group]: false }).success, false);
  }
  settingsSchema.parse(settingsDefinition.defaults);
  assert.equal(Object.hasOwn(settingsDefinition.fields, 'seo'), false);
  for (const name of ['blog', 'services', 'pseoServices', 'pseoIndustries', 'locations']) {
    const parser = collectionSchemas[name];
    // Isolate the group from required collection fields.
    const group = parser.shape.seo;
    assert.deepEqual(group.parse({ noindex: false, image: '/social.jpg', __unknown: true }), { image: '/social.jpg', noindex: false });
    assert.deepEqual(group.parse({}), {});
    assert.deepEqual(group.parse({ noindex: false }), { noindex: false });
    assert.deepEqual(group.parse({ noindex: true }), { noindex: true });
    assert.equal(group.safeParse({ noindex: 'false' }).success, false);
    assert.equal(group.safeParse(false).success, false);
  }
  console.log(`${Object.keys(pageDefinitions).length} fixed defaults plus settings: shared SEO/group/boolean checks passed`);
  console.log(`Contract exercise: ${count} retained fixtures passed; Date remains non-coercing`);
}
